"""empty message

Revision ID: 8bbea309e791
Revises: ac1a9e210cd6
Create Date: 2023-06-14 15:36:57.321572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbea309e791'
down_revision = 'ac1a9e210cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentators', sa.Column('untilDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commentators', 'untilDate')
    # ### end Alembic commands ###
