"""empty message

Revision ID: ac1a9e210cd6
Revises: fde135b2a98c
Create Date: 2023-06-07 17:53:15.165672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1a9e210cd6'
down_revision = 'fde135b2a98c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultants', sa.Column('untilDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultants', 'untilDate')
    # ### end Alembic commands ###
