"""empty message

Revision ID: fde135b2a98c
Revises: 
Create Date: 2023-05-31 14:00:30.934546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde135b2a98c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('usage', sa.Boolean(), nullable=True),
    sa.Column('promt', sa.String(), nullable=True),
    sa.Column('channels', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('apiId', sa.Integer(), nullable=True),
    sa.Column('apiHash', sa.String(), nullable=True),
    sa.Column('stringConnection', sa.String(), nullable=True),
    sa.Column('proxyHttp', sa.String(), nullable=True),
    sa.Column('proxyIp', sa.String(), nullable=True),
    sa.Column('proxyPort', sa.Integer(), nullable=True),
    sa.Column('proxyPass', sa.String(), nullable=True),
    sa.Column('proxyUser', sa.String(), nullable=True),
    sa.Column('is_humanity', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('promt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('idTelegram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('promts')
    op.drop_table('consultants')
    op.drop_table('commentators')
    # ### end Alembic commands ###
